# Generated by Django 3.1.3 on 2020-11-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
